POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

POST http://localhost:3333/events/899e261b-2560-407c-ac7f-d5813faa27c1/attendees
Content-Type: application/json

{
    "name": "Nathan Willian Patrzyk",
    "email": "nathanpatrzyk11@gmail.com"
}

###

GET http://localhost:3333/events/899e261b-2560-407c-ac7f-d5813faa27c1